import { createSlice } from "@reduxjs/toolkit";

const initialState = [
  {
    iphones: [
      {
        id: 1,
        productName: "iPhone 15 Pro",
        description: "From $999 or $41.62/mo. for 24 mo.*",
        price: 999.0,
        param: "iphone-15-pro",
        productImage: "./images/iphones/iphone15pro.png",
      },
      {
        id: 2,
        productName: "iPhone 15",
        description: "From $799 or $33.29/mo. for 24 mo.*",
        price: 799.0,
        param: "iphone-15",
        productImage: "./images/iphones/iphone15.png",
      },
      {
        id: 3,
        productName: "iPhone 14",
        description: "From $699 or $29.12/mo. for 24 mo.*",
        price: 799.0,
        param: "iphone-14",
        productImage: "./images/iphones/iphone14.png",
      },
      {
        id: 4,
        productName: "iPhone 13",
        description: "From $599 or $24.95/mo. for 24 mo.*",
        price: 799.0,
        param: "iphone-13",
        productImage: "./images/iphones/iphone13.png",
      },
      {
        id: 5,
        productName: "iPhone SE",
        description: "From $599 or $24.95/mo. for 24 mo.*",
        price: 799.0,
        param: "iphone-se",
        productImage: "./images/iphones/iphonese.png",
      },
    ],
  },
  {
    ipads: [
      {
        id: 6,
        productName: "iPad Pro",
        description: "From $999 or $83.25/mo. for 12 mo.*",
        price: 999.0,
        param: "ipad-pro",
        productImage: "./images/ipads/ipad_pro.png",
      },
      {
        id: 7,
        productName: "iPad Air",
        description: "From $599 or $49.91/mo. for 12 mo.*",
        price: 599.0,
        param: "ipad-air",
        productImage: "./images/ipads/ipad_air.png",
      },
      {
        id: 8,
        productName: "iPad",
        description: "From $349 or $29.08/mo. for 12 mo.*",
        price: 349.0,
        param: "ipad",
        productImage: "./images/ipads/ipad_10th_gen.png",
      },
      {
        id: 9,
        productName: "iPad mini",
        description: "From $449 or $41.58/mo. for 12 mo.*",
        price: 449.0,
        param: "ipad-mini",
        productImage: "./images/ipads/ipad_mini.png",
      },
    ],
  },
  {
    macbooks: [
      {
        id: 10,
        productName: "MacBook Air",
        description: "From $999 or $83.25/mo. for 12 mo.*",
        price: 999.0,
        param: "macbook-air-m3",
        productImage: "./images/computers/macbook_air_13_m2.png",
      },
      {
        id: 11,
        productName: "MacBook Pro",
        description: "From $1599 or $133.25/mo. for 12 mo.*",
        price: 1599.0,
        param: "macbook-pro",
        productImage: "./images/computers/macbook_pro_14.png",
      },
      {
        id: 12,
        productName: "iMac",
        description: "From $1299 or $108.25/mo. for 12 mo.*",
        price: 1299.0,
        param: "imac",
        productImage: "./images/computers/imac.png",
      },
      {
        id: 13,
        productName: "Mac Studio",
        description: "From $1999 or $166.58/mo. for 12 mo.*",
        price: 1999.0,
        param: "mac-studio",
        productImage: "./images/computers/mac-studio.png",
      },
      {
        id: 14,
        productName: "Mac mini",
        description: "From $599 or $49.91/mo. for 12 mo.*",
        price: 599.0,
        param: "mac-mini",
        productImage: "./images/computers/mac-mini.png",
      },
      {
        id: 15,
        productName: "Mac Pro",
        description: "From $6999 or $583.25/mo. for 12 mo.*",
        price: 6999.0,
        param: "mac-pro",
        productImage: "./images/computers/mac-pro-desktop.jpg",
      },
      {
        id: 16,
        productName: "Pro Display XDR",
        description: "From $4999 or $416.58/mo. for 12 mo.*",
        price: 4999.0,
        param: "pro-display-xdr",
        productImage: "./images/computers/proxdr-display.jpg",
      },
      {
        id: 17,
        productName: "Studio Display",
        description: "From $1599 or $133.25/mo. for 12 mo.*",
        price: 1599.0,
        param: "studio-display",
        productImage: "./images/computers/studio-display.png",
      },
    ],
  },
  {
    watches: [
      {
        id: 18,
        productName: "Apple Watch Series 9",
        description: "From $399 or $33.25/mo. for 12 mo.*",
        price: 399.0,
        param: "apple-watch-series-9",
        productImage: "./images/watches/watch1.png",
      },
      {
        id: 19,
        productName: "Apple Watch Ultra 2",
        description: "From $799 or $366.58/mo. for 12 mo.*",
        price: 799.0,
        param: "apple-watch-ultra-2",
        productImage: "./images/watches/watch2.png",
      },
      {
        id: 20,
        productName: "Apple Watch SE",
        description: "From $249 or $20.75/mo. for 12 mo.*",
        price: 249.0,
        param: "apple-watch-se",
        productImage: "./images/watches/watch3.png",
      },
      {
        id: 21,
        productName: "Apple Watch Hermès",
        description: "From $1249 or $3104.08/mo. for 12 mo.*",
        price: 1249.0,
        param: "apple-watch-series-9",
        productImage: "./images/watches/watch4.png",
      },
    ],
  },
  {
    airpods: [
      {
        id: 22,
        productName: "AirPods Pro 2",
        description: "From $249 or $20.75/mo. for 12 mo.**",
        price: 249.0,
        param: "air-pods-pro-2nd-gen",
        productImage: "./images/airpods/airpods_pro_large.png",
      },
      {
        id: 23,
        productName: "AirPods Max",
        description: "From $549 or $45.75/mo. for 12 mo.**",
        price: 549.0,
        param: "air-max",
        productImage: "./images/airpods/airpods_max.png",
      },
      {
        id: 25,
        productName: "Airpods 3",
        description: "From $169 or $10.75/mo. for 12 mo.*",
        price: 169.0,
        param: "airpods-3nd-gen",
        productImage: "./images/airpods/airpods_3gen_large.png",
      },
      {
        id: 24,
        productName: "AirPods 2",
        description: "From $129 or $14.08/mo. for 12 mo.*",
        price: 129.0,
        param: "airpods-2nd-gen",
        productImage: "./images/airpods/airpods_2gen_large.png",
      },
    ],
  },
  {
    footerLinks: [
      "Privacy Policy",
      "Terms of Use",
      "Sales Policy",
      "Legal",
      "Site Map",
    ],
  },
];

const dataBase = createSlice({
  name: "dataBase",
  initialState,
  reducers: {},
});

export default dataBase.reducer;
